import "./globals.css";
import type { Metadata } from "next";
import { Web3Provider } from "@/context/Web3Context";

export const metadata: Metadata = {
  title: "Web3 Dashboard example",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <body>
    <Web3Provider>{children}</Web3Provider>
    </body>
    </html>
  );
}